Mail:
    Smtp:
        Host: smtp.sample.com
        Port: 25
        User: user1
        Password: pass1
    Pop3:
        Host: pop3.sample.com
        Port: 110
        User: user2
        Password: pass2
        CheckPeriod: 00:01:00
    ErrorNotificationRecipients:
        - user1@sample.com
        - user2@sample.com
    ErrorMessageId: 9d165087-9b74-4313-ab90-89be897d3d93
DB:
    ConnectionString: Data Source=server1;Initial Catalog=Database1;Integrated Security=SSPI;
    NumberOfDeadlockRepeats: 5
    DefaultTimeout: 00:05:00